config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get '/', :to => 'listings#index'
  get '/listings/deals', to: 'listings#deals'

  resources :listings
  resources :bookings
  resources :users
  resources :reviews
  resources :inquiries, only: [:new, :create]
  post '/bookings/new', to: 'bookings#new'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews
  has_many :inquiries



  validates :name, uniqueness: true
  validates :name, presence: true
  validates :price, presence: true

  mount_uploader :image, ImageUploader

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :find_listing, only: [:show, :edit, :update, :destroy]
  # before_action :require_login
  # skip_before_action :require_login, only: [:index, :show]
  def index
    if params[:state]
      if params[:state].length != 2
       flash[:notice] = "Please enter a state abbreviation! (NY, NJ, CA)"
       redirect_to listings_path

      else
       @listings = Listing.all.select do |listing|
         listing[:state].downcase == params[:state].downcase
        end

         if @listings.length > 0
            @listings
         else
           flash[:notice] = "No Matches in That State"
           redirect_to listings_path
         end
       end
   else
     @listings = Listing.all.uniq
   end
  end

  def deals
  end

  def show

    if flash[:notice]
        flash[:notice] = "We delivered your inquiry to the owner! Get back to exploring!"
    end
  end

  def new
    @listing = Listing.new
    @states = [
		"AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC",
    "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA",
    "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE",
    "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC",
    "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"]
  end

  def create
    @user = User.find_by(id: session[:user_id])
    @listing = Listing.create(listing_params)
    @listing.user_id = @user.id
    if @listing.valid?
      @listing.state = params[:state]
      @listing.save
      redirect_to @listing
    else
      flash[:error] = @listing.errors.full_messages
      redirect_to new_listing_path
    end
  end

  def edit
    @states = [
		"AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC",
    "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA",
    "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE",
    "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC",
    "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"]
  end

  def update
    @listing.update(listing_params)
    if @listing.valid?
      redirect_to @listing
    else
      flash[:error] = @listing.errors.full_messages
      redirect_to edit_listing_path
    end
  end

  def destroy
    @listing.destroy
    redirect_to listings_path
  end

private

  def require_login
    return head(:forbidden) unless session.include? :user_id
  end

  def find_listing
    @listing = Listing.find_by(id: params[:id])
  end

  def listing_params
    params.require(:listing).permit(:name, :user_id, :price, :image, :state, :city, :address, :listing_id)
  end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_errors.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |msg| %>
    <p> <%= msg %> </p>
  <% end %>
<% end %>


<% if flash[:notice] %>
 <p><%= flash[:notice] %></p>
<% end %>

app/views/listings/_form.erb
<% if flash[:error] %>
  <% flash[:error].each do |error| %>
    <%= error %><br><br>
  <% end %>
<% end %>


<div id="new_listing"><%= form_for @listing do |f| %>

  <%= f.label :name %>:
  <%= f.text_field :name, class: "search_bar" %>

  <%= f.label :price %>:
  <%= f.text_field :price, class: "search_bar"%>

  <%= f.label :state %>:
  <%= select_tag "state", options_for_select(@states), class: "dropdown"  %>

  <%= f.label :city %>:
  <%= f.text_field :city, class: "search_bar"  %>

  <%= f.label :address %>:
  <%= f.text_field :address, class: "search_bar"%><br>

  <label>Upload a photo of your listing:</label>
   <%= f.file_field :image%><br><br>

  <%= f.submit class: "btn"%>
</div>

<% end %>

app/views/listings/deals.erb
<h1>OOOOOOHHHHHH!!!</h1>

<h2>YOU JUST MISSED OUR LAST DEAL! TRY AGAIN IN A FEW MINUTES!</h2>

app/views/listings/edit.erb
<h2 class="page_header">Edit listing</h2>

<%= render "form" %>

app/views/listings/index.erb
<h2 class="title">All listings</h2>

<h3> <%= render 'errors' %>
</h3>
<br>

<div>
  <%= form_tag(listings_path, method: :get) do %>
   <br>
   <%= text_field_tag :state, nil, placeholder: "City, State (NY, CA, etc.)", class: "search_bar" %>  <%=submit_tag 'Search', :class => "btn" %>
  <% end %>
</div>
<br><br><br>

<div class="listings_container">
<% @listings.each do |listing| %>
  <%= link_to listing do %>
  <div class="listing_card">
    <div class="listing_card_img">
      <%= image_tag((listing.image_url(:thumb).to_s), :class => "card_img") %>
    </div>
    <div class="listing_card_name">
      <%= link_to listing.name, listing %>
      <% end %>
    </div>
  </div>
<% end %>
</div>

app/views/listings/new.erb
<h2 class="page_header">Add a new listing</h2>

<%= render "form" %>

app/views/listings/show.erb
<div class="listing_container">

  <div id="left">
    <div id="listing_header"><%= @listing.name %></div>
<%= render 'errors' %>
    <div id="listing_image"><%= image_tag(@listing.image_url.to_s) %></div>
  </div>

  <div id="right">
    Listing details:<br>
    Price per night: $<%= @listing.price %><br>
    State: <%= @listing.state %><br>
    City: <%= @listing.city %><br>
    Address: <%= @listing.address %><br>
    <div class="listing_links"> Owner: <%=link_to @listing.user.name, @listing.user %></div>
  </div>

</div>

  <div id="review"><div id="reviews_label">Reviews:</div> <% @listing.reviews.each do |review| %><br>
            Review by: <%= review.user.name %><br>
            Rating: <%= review.rating %>/5<br>
            Description: <%= review.description %><br>
    <% if current_user && current_user.name == review.user.name %>
    <div class="listing_links"><%= link_to 'Edit this review', edit_review_path %></div> |
    <div class="listing_links"><%= link_to 'Delete this review', review_path, method: :delete %></div>
    <% end %>
            <% end %>

  </div>
  <br>
  <br>

<% if current_user != @listing.user && current_user %>
  <div class="listing_links"><%= link_to 'Write a review', new_review_path(flash[:listing_id] = @listing.id) %></div>
<% end %>
<br><br>

<% if current_user != @listing.user && current_user %>
  <%=button_to 'Book this place', '/bookings/new', params: {listing_id: @listing.id}, class: "btn"%>
<% end %>


<% if current_user == @listing.user %>
<div class="listing_links"><%= link_to "Edit this listing", edit_listing_path %></div><br>
<% end %>

<% if current_user == @listing.user %>
  <div class="listing_links"><%= link_to "Delete this listing", @listing, method: :delete, data: { confirm: 'Are you sure you would like to delete this listing?'} %></div></br>
<% end %>