config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get '/', :to => 'listings#index'
  get '/listings/deals', to: 'listings#deals'

  resources :listings
  resources :bookings
  resources :users
  resources :reviews
  resources :inquiries, only: [:new, :create]
  post '/bookings/new', to: 'bookings#new'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :matched_user, class_name: "User"
  has_one :listing

  validate :asynchrony?

  after_create :create_inverse, unless: :has_inverse?
  after_destroy :destroy_inverses, if: :has_inverse?

  def create_inverse
    self.class.create(inverse_match_options)
  end

  def destroy_inverses
    inverses.destroy_all
  end

  def has_inverse?
    self.class.exists?(inverse_match_options)
  end

  def inverses
    self.class.where(inverse_match_options)
  end

  def inverse_match_options
    { matched_user_id: user_id, user_id: matched_user_id }
  end

  def asynchrony?
    if self.listing_id
      @@listing_id = self.listing_id
      @@check_in_date = self.check_in_date
      @@check_out_date = self.check_out_date
      @@price = Listing.find(self.listing_id).price
    else

      self.check_in_date = @@check_in_date
      self.check_out_date = @@check_out_date
      self.listing_id = @@listing_id
      @@price = Listing.find(self.listing_id).price

    end

      in_date = self.check_in_date.split("/")
      in_year = in_date[-1]
      in_month = in_date[0]
      in_day = in_date[1]
      out_date = self.check_out_date.split("/")
      out_year = out_date[-1]
      out_month = out_date[0]
      out_day = out_date[1]




    if out_year < in_year || out_year == in_year && out_month < in_month ||
      out_year == in_year && out_month == in_month && out_day < in_day
      errors.add(:check_in_date, "cannot be later than your check out date")

    else
      
        total = @@price * ((out_year.to_i - in_year.to_i) * 365) + ((out_month.to_i - in_month.to_i) * 30) + (out_day.to_i - in_day.to_i)
        self.total = total
    end
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: [:edit, :show, :update, :destroy]

  def show


    if params[:listing_id]
      @confirmation_num = @booking
      @listing = Listing.find(@booking.listing_id)
      @price = @booking.total
      @listing_name = @listing.name
      @check_in = "#{eval(@booking.check_in_date)[2]}/#{eval(@booking.check_in_date)[3]}/#{eval(@booking.check_in_date)[1]} "
      @check_out = "#{eval(@booking.check_out_date)[2]}/#{eval(@booking.check_out_date)[3]}/#{eval(@booking.check_out_date)[1]} "
    else
      @listing = Listing.find(session[:listing_id])
      @price = Booking.find(session[:booking_id]).total
      @listing_name = @listing.name
      @check_in = session[:check_in_date]
      @check_out = session[:check_out_date]
      @confirmation_num = rand(192912312...123123123123)

    end


  end

  def new

    if params[:listing_id]

      @listing = Listing.find(params[:listing_id])
      @booking = Booking.new(:listing_id => params[:listing_id])
      @user = User.find(session[:user_id])
      @listing_name = @listing.name
      @owner = User.find(@listing.user_id)
      session[:listing_id] = @listing.id
      session[:owner_id] = @owner.id
      session[:user_id] = @user.id

    else

      @listing = Listing.find(session[:listing_id])
      @booking = Booking.new(:listing_id => session[:listing_id])
      @user = User.find(session[:user_id])
      @listing_name = @listing.name
      @owner = User.find(@listing.user_id)

    end
  end

  def create
    @year_in= booking_params[:"check_in_date(1i)"]
    @month_in= booking_params[:"check_in_date(2i)"]
    @day_in= booking_params[:"check_in_date(3i)"]
    @year_out= booking_params[:"check_out_date(1i)"]
    @month_out= booking_params[:"check_out_date(2i)"]
    @day_out= booking_params[:"check_out_date(3i)"]
    @check_in = @month_in + "/" + @day_in + "/" + @year_in
    @check_out = @month_out + "/" + @day_out + "/" + @year_out
    @booking = Booking.new
    @booking.user_id = params[:user_id]
    @booking.matched_user_id = params[:matched_user_id]
    @listing = Listing.find(params[:listing_id])
    @listing_id = @listing.id
    @booking.listing_id = @listing_id
    @booking.check_in_date = @check_in
    @booking.check_out_date = @check_out

    if @booking.save

      session[:listing_id] = @listing_id
      session[:booking_id] = @booking.id
      session[:matched_user_id] = @booking.matched_user_id
      session[:check_in_date] = @booking.check_in_date
      session[:check_out_date] = @booking.check_out_date
      redirect_to '/bookings/show', :listing_id => @listing_id, :user_id => session[:user_id], session[:booking_id] => @booking_id, session[:matched_user_id] => @booking.matched_user_id,    session[:check_in_date] => @booking.check_in_date, session[:check_out_date] => @booking.check_out_date
    else

      flash[:error] = @booking.errors.full_messages
      # store listing id in session
      session[:listing_id] = @listing_id

      redirect_to '/bookings/new', :listing_id => @listing_id
    end

  end



  def edit
  end

  def update
  end

  def destroy
  end

  private
    def find_booking
      @booking = Booking.find_by(id: params[:id])
    end

    def booking_params
      params.require(:booking).permit(:user_id, :owner_id, :listing_id, :check_in_date, :check_out_date)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_errors.erb
<% if flash[:error] %>
  <% flash[:error].each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>

app/views/bookings/_form.erb
<div class="all_set"> Hey <%= @user.name %>! You're all set to book <%=@listing_name%>!  Just select your check-in and check-out dates below!</div>

  <div class"new_booking"><%= form_for @booking do |f|%>


  <p> Check in Date:
  <%=   date_select("booking", "check_in_date", start_year: 2018, prompt: { day: 'Select day', month: 'Select month', year: 'Select year' })  %>
  </p>

  <p> Check out Date:
  <%=   date_select("booking", "check_out_date", start_year: 2018, prompt: { day: 'Select day', month: 'Select month', year: 'Select year' })  %>
  </p>

  <p> <%= f.submit "Check Availability", class: "btn" %>
  </p>

  <p>Reference Number : <%= @booking %>
  </p>

  <%= hidden_field_tag 'listing_id', @listing.id  %>
  <%= hidden_field_tag 'user_id', @user.id  %>
  <%= hidden_field_tag 'matched_user_id', @owner.id  %>

  <p> <%= @user.name %>, don't forget! If you have any questions please contact <%=@owner.name%>!  Just click here to send your message!
  <div id="contact_owner"><%= link_to "Contact Owner", new_inquiry_path, :listing_id => @listing.id, :user_id => @user.id, :owner_id => @owner.id %></div>
  </p>
</div>

<% end %>

app/views/bookings/new.erb
  <body>
    <%= render 'errors' %>
    <%= render 'form' %>
  </body>

app/views/bookings/show.erb
<div class="title">Congratulations You're All Booked!</div>
<div id="sub_title"><%= @listing.name %></div> <br>
<div class="all_set">
  Total: $<%= @price %><br>
  Dates: <%=@check_in%> to <%= @check_out %>
</div>