config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get '/', :to => 'listings#index'
  get '/listings/deals', to: 'listings#deals'

  resources :listings
  resources :bookings
  resources :users
  resources :reviews
  resources :inquiries, only: [:new, :create]
  post '/bookings/new', to: 'bookings#new'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :matched_users, through: :bookings
  has_many :listings
  has_many :reviews
  has_many :inquiries


  has_secure_password

  validates :email, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]


  def show

  end

  def new
    @user = User.new
  end

  def create
   @user = User.create(user_params)

   if @user.valid?
     session[:user_id] = @user.id
     redirect_to @user
   else

     flash[:error] = @user.errors.full_messages
     redirect_to new_user_path
   end
  end

  def edit

  end

  def update

  end

  def destroy

  end

private

  def find_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :user_id, :matched_user_id, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.erb
<% if flash[:error] %>
  <% flash[:error].each do |error| %>
  <%= error %><br>
  <% end %>
<% end %>

app/views/users/new.erb
<h2 class="page_header">Create an account</h2>

<%= render 'errors' %>

<div id="create_account"><%= form_for :user, url: '/users' do |f| %>

  <%= f.label :name %></>
  <%= f.text_field :name, class: "search_bar" %>

  <%= f.label :email %>
  <%= f.text_field :email, class: "search_bar" %>
  <%= f.label :password %>
  <%= f.password_field :password, class: "search_bar" %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "search_bar" %><br><br>

  <%= f.submit class: "btn" %>

<% end %>
</div>

app/views/users/show.erb
<h2 class="page_header"><%= @user.name %></h2>

  <% if current_user == @user %>
    <h2 class="sub_header">My Properties</h2>
      <% @user.listings.each do |listing| %>
        <div><%= image_tag(listing.image_url(:thumb).to_s) %></div>
        <div class="listing_links"><%=link_to listing.name, listing %></div><br><br>
      <% end %>

  <div id="add_listing"><%= link_to "Add a listing", new_listing_path %></div>

    <h2 class="sub_header"> My Bookings</h2>
      <div id="bookings_info"><% @user.bookings.each do |booking| %>
        Booking # <%=booking.id  %>:
    <p>
      Name: <%=  Listing.find(booking.listing_id).name %> <br>
      Total: $<%= booking.total %> <br>
      Check-In: <%= booking.check_in_date %> <br>
      Check-Out: <%= booking.check_out_date %> <br>
      Owner: <%= User.find(booking.matched_user_id).name %> <br>
    </p>
      <% end %>
      </div>
      <% else %>
    <p>
      <div class="sub_header">Properties:</div>
        <% @user.listings.each do |listing| %><br><br>
        <%= image_tag(listing.image_url(:thumb).to_s) %><br>
        <div class="listing_links"> <%=link_to listing.name, listing %><br></div>
        <% end %>
    </p>
  <% end %>