config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get '/', :to => 'listings#index'
  get '/listings/deals', to: 'listings#deals'

  resources :listings
  resources :bookings
  resources :users
  resources :reviews
  resources :inquiries, only: [:new, :create]
  post '/bookings/new', to: 'bookings#new'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StayHero</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet">
  </head>
  <body>
      <div id="logo"> <%= link_to "StayHero", listings_path %> <%= image_tag("home2.png") %></div>

      <div id="navBar">

        <% if current_user %>
        <%= link_to "All listings", listings_path %> <span class="bar"> |</span>
            <%= link_to "View profile", current_user %> <span class="bar"> |</span>
            <a style="text-decoration:none" href=" https://www.airbnb.com/">Recommended spots </a> <span class="bar"> |</span>
            <%= link_to "Last Minute Deals", listings_deals_path %> <span class="bar"> |</span>
            <%= link_to "Logout", logout_path, method: :delete %>
          <% else %>
            <%= link_to "All listings", listings_path %> <span class="bar"> |</span>
            <%= link_to "Login", login_path %>
          <% end %>

      </div>

    <div id="body">
      <%= yield %>
    </div>
  </body>
  <div class="grass"> <%= image_tag("grass.jpg") %></div>
</html>